### ISSUE TITLE
RAS integration on profile page

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#324] opened 2022-02-14 23:22 UTC
Depending on how this is included in the authn response, changes to profile page `visible-columns` or `visible-foreign-keys` annotations will be needed for proper display. This might just be a uid that is displayed as text.

If this is part of the "attributes" array on the authn response object, this might be an object with the uid set as the "id" property. This will be a group that is not a globus group so display of this shouldn't use any special internal logic to try and treat it like a globus group.

**Comment by karlcz** [comment] 2022-02-15 23:11
closing this as a duplicate of #311

**Closed by karlcz** 2022-02-15 23:11 UTC
