### ISSUE TITLE
Statistics about history of saved searches

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#240] opened 2021-09-10 19:25 UTC
Creating this issue based on @ACharbonneau 's comment in [issue 51 in dashboard repo](https://github.com/nih-cfde/dashboard/issues/51#issuecomment-908661782)
> I think this doesn't need to be a user feature, however I would like to be able to get a monthly? quarterly? Some time period readout of what searches people did if that's possible. For tracking/reporting. Absolutely can just be a csv or something that I parse

**Comment by ACharbonneau** [comment] 2021-09-15 15:16
I think this is a duplicate of https://github.com/nih-cfde/cfde-deriva/issues/247

**Closed** 2021-09-15 15:17 UTC
